version: "3"

services:
  web:
    image: registry.gitlab.com/notch8/ucsc-docker/webapp-unit-test:latest
    build:  
      context: .
      dockerfile: webapp-dockerfile
      args:
        BRANCH: ${BRANCH}
    container_name: hycruz
    volumes:
     - "dams_derivatives:/dams_derivatives:Z"
    depends_on:
      - "db"
      - "repo"
      - "index"
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - BRANCH
    networks:
      front-tier:
        aliases: 
          - hycruz
          - hyrax
          - app
          - application
      back-tier:
        aliases:
          - hycruz
          - hyrax
          - app
          - application
  repo:
    image: registry.gitlab.com/notch8/ucsc-docker/repo-unit-test:latest
    build:  
      context: .
      dockerfile: repo-dockerfile
    container_name: fcrepo
    ports:
      - "8082:8080"
    networks:
      back-tier:
        aliases:
          - repository
          - fedora
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    env_file:
      - .env
    restart: always
    networks:
      back-tier:
        aliases:
          - database
          - mysql
  index:
    image: solr:7.7
    container_name: solr
    command: "bash -c 'precreate-core hycruz /opt/config && precreate-core hycruz-test /opt/config && solr-foreground'"
    ports: 
      - "8983:8983"
    volumes:
      - "./solr_conf:/opt/config:Z"
      - "index-data:/opt/solr/server/solr:Z"
    networks:
      back-tier:
        aliases:
          - solr
volumes:
  dams_ingest:
  dams_derivatives:
  index-data:
networks:
  front-tier:
  back-tier:
