version: "3"

services:
  web:
    image: registry.gitlab.com/notch8/ucsc-docker/webapp:latest
    build:  
      context: .
      dockerfile: webapp-dockerfile
    container_name: hycruz
    volumes:
     - "dams_derivatives:/dams_derivatives:Z"
    depends_on:
      - "db"
      - "repo"
      - "index"
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      front-tier:
        aliases: 
          - hycruz
          - hyrax
          - app
          - application
      back-tier:
        aliases:
          - hycruz
          - hyrax
          - app
          - application
  repo:
    image: registry.gitlab.com/notch8/ucsc-docker/repo:latest
    build:  
      context: .
      dockerfile: repo-dockerfile
    container_name: fcrepo
    ports:
      - "8082:8080"
    networks:
      back-tier:
        aliases:
          - repository
          - fedora
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    env_file:
      - .env
    restart: always
    networks:
      back-tier:
        aliases:
          - database
          - mysql
  index:
    image: registry.gitlab.com/notch8/ucsc-docker/index:latest
    build: 
      context: .
      dockerfile: index-dockerfile
    container_name: solr
    command: "bash -c 'solr-foreground'"
    ports: 
      - "8983:8983"
    environment:
      SOLR_HOME: /opt/solr/server/solr
    networks:
      back-tier:
        aliases:
          - solr
#  worker:
#    image: registry.gitlab.com/notch8/ucsc-docker/worker:latest
#    build:  
#      context: .
#      dockerfile: worker-dockerfile
#    container_name: worker
#    volumes:
#     - "dams_derivatives:/dams_derivatives:Z"
#     - "./example_media:/srv/hycruz/public/example_media"
#    env_file:
#      - .env
#      - .env.development
#    depends_on:
#      - "db"
#      - "repo"
#      - "index"
#      - "redis"
#    networks:
#      back-tier:
#        aliases:
#          - sidekiq
#          - worker_1
#  images:
#    image: registry.gitlab.com/notch8/ucsc-docker/images:latest
#    build:  
#      context: .
#      dockerfile: cantaloupe-dockerfile
#    container_name: cantaloupe
#    depends_on:
#      - "repo"
#    ports:
#      - "8182:8182"
#      - "8183:8183"
#    volumes:
#      - "../dams_derivatives:/dams_derivatives:z"
#    networks:
#      front-tier:
#        aliases: 
#          - images
#          - cantaloupe
#          - hycruz-images
#      back-tier:
#        aliases:
#          - images
#          - cantaloupe
#          - hycruz-images          
volumes:
  dams_ingest:
  dams_derivatives:
networks:
  front-tier:
  back-tier:
