version: "3"

services:
  webapp:
    build:  
      context: .
      dockerfile: webapp-dockerfile
    container_name: hycruz
    volumes:
     - "derivatives:/dams_derivatives:z"
     - "application:/srv/hycruz:z"
     - "gems:/srv/bundle:Z"
     - "dams_ingest:/dams_ingest"
     - "scooby_snacks:/srv/scooby_snacks"
     - "samvera_hls:/srv/samvera_hls"
     - "bulk_ops:/srv/bulk_ops"
    environment: 
      - IIIF_SERVER_URL=http://127.0.0.1:8182/iiif/2/
    depends_on:
      - "db"
      - "repo"
      - "index"
      - "redis"
    links:
      - "db"
      - "repo"
      - "index"
      - "redis"
    ports:
      - "80:3000"
    networks:
      front-tier:
        aliases: 
          - hycruz
          - hyrax
          - app
          - application
      back-tier:
        aliases:
          - hycruz
          - hyrax
          - app
          - application
  worker:
    build:  
      context: .
      dockerfile: worker-dockerfile
    container_name: worker
    volumes:
     - "derivatives:/dams_derivatives:z"
     - "application:/srv/hycruz:z"
     - "gems2:/srv/bundle:Z"
     - "dams_ingest:/dams_ingest"
     - "scooby_snacks:/srv/scooby_snacks"
     - "samvera_hls:/srv/samvera_hls"
     - "bulk_ops:/srv/bulk_ops"
    depends_on:
      - "db"
      - "repo"
      - "index"
      - "redis"
    links:
      - "db"
      - "repo"
      - "index"
      - "redis"
    networks:
      back-tier:
        aliases:
          - sidekiq
          - worker_1
  repo:
    build:  
      context: .
      dockerfile: repo-dockerfile
    container_name: fcrepo
    volumes:
      - "repository-data:/opt/fcrepo/data:Z"
    ports:
      - "8080:8080"
    networks:
      back-tier:
        aliases:
          - repository
          - fedora
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_DATABASE: hyrax_dev
      MYSQL_USER: hyrax_user
      MYSQL_ROOT_PASSWORD: potentialmidday
      MYSQL_PASSWORD: potentialmidday
    restart: always
    volumes:
      - "database-data:/var/lib/mysql:Z"
    networks:
      back-tier:
        aliases:
          - database
          - mysql
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      back-tier:
        aliases:
          - queue
  index:
    image: solr
    container_name: solr
    ports: 
      - "8983:8983"
    volumes:
      - "index-data:/opt/solr/server/solr/hycruz:Z"
      - "index-data-test:/opt/solr/server/solr/hycruz-test:Z"
    environment:
      SOLR_HOME: /opt/solr/server/solr
    networks:
      back-tier:
        aliases:
          - solr
  images:    
    build:  
      context: .
      dockerfile: cantaloupe-dockerfile
    container_name: cantaloupe
    depends_on:
      - "repo"
    ports:
      - "8182:8182"
      - "8183:8183"
    volumes:
      - "derivatives:/dams_derivatives:z"
      - "cantaloupe-log:/srv/cantaloupe-log:Z"
      - "cantaloupe-cache:/srv/cantaloupe-cache:Z"
    networks:
      front-tier:
        aliases: 
          - images
          - cantaloupe
          - hycruz-images
      back-tier:
        aliases:
          - images
          - cantaloupe
          - hycruz-images
volumes:
  application:
    driver_opts:
      type: none
      device: /srv/hyrax 
      o: bind
  dams_ingest:   
    driver_opts:
      type: none
      device: /srv/dams_ingest 
      o: bind
  database-data:
  derivatives:   
    driver_opts:
      type: none
      device: /srv/dams_derivatives
      o: bind
  gems:
  gems2:
  cantaloupe-log:
  cantaloupe-cache:
  index-data:
  index-data-test:
  redis-data:
  repository-data:
  scooby_snacks:
    driver_opts:
      type: none
      device: /srv/scooby_snacks 
      o: bind
  samvera_hls:
    driver_opts:
      type: none
      device: /srv/samvera_hls
      o: bind
  bulk_ops:
    driver_opts:
      type: none
      device: /srv/bulk_ops
      o: bind
networks:
  front-tier:
  back-tier:
