development:
  repo: <%= ENV.fetch('GITHUB_REPO') %>
  client_id: <%= ENV.fetch('GITHUB_CLIENT_ID') %>
  client_secret: <%= ENV.fetch('GITHUB_CLIENT_SECRET') %> 
  webhook_secret: <%= ENV.fetch('GITHUB_WEBHOOK_SECRET') %> 
test:
  repo: <%= ENV.fetch('GITHUB_REPO') %>
  client_id: <%= ENV.fetch('GITHUB_CLIENT_ID') %>
  client_secret: <%= ENV.fetch('GITHUB_CLIENT_SECRET') %> 
  webhook_secret: <%= ENV.fetch('GITHUB_WEBHOOK_SECRET') %> 
